In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset_train=pd.read_csv('/content/drive/MyDrive/Train.csv')
training_set=dataset_train.iloc[:, 5:6].values

In [ ]:
print(training_set)

In [3]:
from sklearn.preprocessing import MinMaxScaler
sc=MinMaxScaler(feature_range=(0, 1))
training_set_scaled=sc.fit_transform(training_set)
print(training_set_scaled)

[[0.72788295]
 [0.68527877]
 [0.65229488]
 [0.70406125]
 [0.61564612]
 [0.66054085]
 [0.62526642]
 [0.57029328]
 [0.5281472 ]
 [0.46676053]
 [0.54280671]
 [0.6390097 ]
 [0.67382603]
 [0.72284374]
 [0.67290981]
 [0.75124653]
 [0.7397938 ]
 [0.94090387]
 [0.97709452]
 [0.93311601]
 [0.89692536]
 [0.87172934]
 [0.93632277]
 [0.90013212]
 [0.81034266]
 [0.82362784]
 [0.94411064]
 [1.        ]
 [0.89509292]
 [0.8795172 ]
 [0.87585232]
 [0.25419772]
 [0.23358279]
 [0.22258816]
 [0.19922458]
 [0.10943511]
 [0.14012845]
 [0.10622834]
 [0.16028527]
 [0.15570417]
 [0.19922458]
 [0.16619946]
 [0.29845384]
 [0.34301782]
 [0.2447854 ]
 [0.21418722]
 [0.21661565]
 [0.15299087]
 [0.14861971]
 [0.12870661]
 [0.1092792 ]
 [0.04128325]
 [0.01165645]
 [0.03205523]
 [0.04759716]
 [0.04468305]
 [0.        ]
 [0.13064935]
 [0.06265341]
 [0.05391107]
 [0.0529397 ]
 [0.14716265]
 [0.19913098]
 [0.28024043]
 [0.35017911]
 [0.3768918 ]
 [0.40214744]
 [0.32880896]
 [0.38611982]
 [0.35455028]
 [0.49151354]
 [0.56

In [4]:
x_train=[]
y_train=[]
for i in range (20, 78):
  x_train.append(training_set_scaled[i-20:i, 0])
  y_train.append(training_set_scaled[i, 0])
x_train, y_train=np.array(x_train), np.array(y_train)

In [ ]:
print(x_train)

In [ ]:
print(y_train)

In [5]:
x_train=np.reshape(x_train, (x_train.shape[0], x_train.shape[1], 1))
print(x_train)

[[[0.72788295]
  [0.68527877]
  [0.65229488]
  ...
  [0.94090387]
  [0.97709452]
  [0.93311601]]

 [[0.68527877]
  [0.65229488]
  [0.70406125]
  ...
  [0.97709452]
  [0.93311601]
  [0.89692536]]

 [[0.65229488]
  [0.70406125]
  [0.61564612]
  ...
  [0.93311601]
  [0.89692536]
  [0.87172934]]

 ...

 [[0.04468305]
  [0.        ]
  [0.13064935]
  ...
  [0.54639598]
  [0.63916187]
  [0.67704533]]

 [[0.        ]
  [0.13064935]
  [0.06265341]
  ...
  [0.63916187]
  [0.67704533]
  [0.71978564]]

 [[0.13064935]
  [0.06265341]
  [0.05391107]
  ...
  [0.67704533]
  [0.71978564]
  [0.76786848]]]


In [19]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

regressor=Sequential()
regressor.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1], 1)))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50, return_sequences=True))
regressor.add(Dropout(0.2))
regressor.add(LSTM(units=50))
regressor.add(Dropout(0.2))
regressor.add(Dense(units=1))
regressor.compile(optimizer='adam', loss='mean_squared_error')
regressor.fit(x_train, y_train, epochs=100, batch_size=10)


Epoch 1/100
6/6 [==============================] - 6s 29ms/step - loss: 0.1829
Epoch 2/100
6/6 [==============================] - 0s 28ms/step - loss: 0.1057
Epoch 3/100
6/6 [==============================] - 0s 29ms/step - loss: 0.0912
Epoch 4/100
6/6 [==============================] - 0s 29ms/step - loss: 0.0986
Epoch 5/100
6/6 [==============================] - 0s 30ms/step - loss: 0.0860
Epoch 6/100
6/6 [==============================] - 0s 28ms/step - loss: 0.0851
Epoch 7/100
6/6 [==============================] - 0s 30ms/step - loss: 0.0876
Epoch 8/100
6/6 [==============================] - 0s 29ms/step - loss: 0.0834
Epoch 9/100
6/6 [==============================] - 0s 29ms/step - loss: 0.0784
Epoch 10/100
6/6 [==============================] - 0s 28ms/step - loss: 0.0793
Epoch 11/100
6/6 [==============================] - 0s 30ms/step - loss: 0.0788
Epoch 12/100
6/6 [==============================] - 0s 30ms/step - loss: 0.0658
Epoch 13/100
6/6 [==============================]

In [20]:
dataset_test=pd.read_csv('/content/drive/MyDrive/Test.csv')
real_stock_price=dataset_test.iloc[:, 5:6].values
print(real_stock_price)

[[133.35]
 [133.91]
 [133.66]
 [136.04]
 [138.02]
 [138.22]
 [135.34]
 [134.83]
 [135.03]
 [132.87]
 [133.59]
 [134.76]
 [134.21]
 [132.94]
 [131.58]
 [130.82]
 [129.35]
 [128.82]
 [136.1 ]
 [134.26]
 [132.52]
 [134.5 ]]


In [21]:
dataset_total=pd.concat((dataset_train['adjusted_close'], dataset_test['adjusted_close']), axis=0)
inputs=dataset_total[len(dataset_total)-len(dataset_test)-20:].values
inputs=inputs.reshape(-1, 1)
inputs=sc.transform(inputs)
x_test=[]
for i in range(20, 43):
  x_test.append(inputs[i-20:i, 0])
x_test=np.array(x_test)
x_test=np.reshape(x_test, (x_test.shape[0], x_test.shape[1], 1))
predicted_stock_price=regressor.predict(x_test)
predicted_stock_price=sc.inverse_transform(predicted_stock_price)

In [22]:
print(predicted_stock_price[22])

[121.27536]


In [23]:
import math
from sklearn.metrics import mean_squared_error
rmse = math.sqrt(mean_squared_error(real_stock_price, predicted_stock_price[0:22]))
print(rmse)

7.017523723657283


In [17]:
from sklearn.metrics import mean_absolute_error as mae
error = mae(real_stock_price, predicted_stock_price[0:22])
print(error)

6.223055544766511
